{
  "out": [
    "/lib/python3.9/site-packages/zope/exceptions/__init__.py",
    "/lib/python3.9/site-packages/zope/exceptions/__pycache__/__init__.cpython-39.pyc",
    "/lib/python3.9/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-39.pyc",
    "/lib/python3.9/site-packages/zope/exceptions/__pycache__/interfaces.cpython-39.pyc",
    "/lib/python3.9/site-packages/zope/exceptions/__pycache__/log.cpython-39.pyc",
    "/lib/python3.9/site-packages/zope/exceptions/exceptionformatter.py",
    "/lib/python3.9/site-packages/zope/exceptions/interfaces.py",
    "/lib/python3.9/site-packages/zope/exceptions/log.py",
    "/lib/python3.9/site-packages/zope/exceptions/tests/__init__.py",
    "/lib/python3.9/site-packages/zope/exceptions/tests/__pycache__/__init__.cpython-39.pyc",
    "/lib/python3.9/site-packages/zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-39.pyc",
    "/lib/python3.9/site-packages/zope/exceptions/tests/__pycache__/test_log.cpython-39.pyc",
    "/lib/python3.9/site-packages/zope/exceptions/tests/test_exceptionformatter.py",
    "/lib/python3.9/site-packages/zope/exceptions/tests/test_log.py",
    "/lib/python3.9/site-packages/zope.exceptions-4.4-py3.9-nspkg.pth",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/INSTALLER",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/LICENSE.txt",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/METADATA",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/RECORD",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/REQUESTED",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/WHEEL",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/direct_url.json",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/namespace_packages.txt",
    "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/top_level.txt",
    "/nix-support/propagated-build-inputs"
  ]
}