{
  "meta": {
    "desc": "Exception interfaces and implementations",
    "desc_long": null,
    "home": "https://pypi.python.org/pypi/zope.exceptions",
    "license": {
      "deprecated": false,
      "free": true,
      "fullName": "Zope Public License 2.0",
      "redistributable": true,
      "shortName": "zpl20",
      "spdxId": "ZPL-2.0",
      "url": "https://spdx.org/licenses/ZPL-2.0.html"
    },
    "maintainers": [
      {
        "email": "cillian.deroiste@gmail.com",
        "github": "cillianderoiste",
        "githubId": 643494,
        "name": "Cillian de R\u00f3iste"
      }
    ]
  },
  "outputs": {
    "out": [
      "/lib/python3.9/site-packages/zope/exceptions/__init__.py",
      "/lib/python3.9/site-packages/zope/exceptions/__pycache__/__init__.cpython-39.pyc",
      "/lib/python3.9/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-39.pyc",
      "/lib/python3.9/site-packages/zope/exceptions/__pycache__/interfaces.cpython-39.pyc",
      "/lib/python3.9/site-packages/zope/exceptions/__pycache__/log.cpython-39.pyc",
      "/lib/python3.9/site-packages/zope/exceptions/exceptionformatter.py",
      "/lib/python3.9/site-packages/zope/exceptions/interfaces.py",
      "/lib/python3.9/site-packages/zope/exceptions/log.py",
      "/lib/python3.9/site-packages/zope/exceptions/tests/__init__.py",
      "/lib/python3.9/site-packages/zope/exceptions/tests/__pycache__/__init__.cpython-39.pyc",
      "/lib/python3.9/site-packages/zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-39.pyc",
      "/lib/python3.9/site-packages/zope/exceptions/tests/__pycache__/test_log.cpython-39.pyc",
      "/lib/python3.9/site-packages/zope/exceptions/tests/test_exceptionformatter.py",
      "/lib/python3.9/site-packages/zope/exceptions/tests/test_log.py",
      "/lib/python3.9/site-packages/zope.exceptions-4.4-py3.9-nspkg.pth",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/INSTALLER",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/LICENSE.txt",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/METADATA",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/RECORD",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/REQUESTED",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/WHEEL",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/direct_url.json",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/namespace_packages.txt",
      "/lib/python3.9/site-packages/zope.exceptions-4.4.dist-info/top_level.txt",
      "/nix-support/propagated-build-inputs"
    ]
  },
  "versions": [
    {
      "first": "02ac13b563c082eaa51e8acdbe492a7961231836",
      "last": "00460bd6e2c89f3b76dcb42032194e6eed0616d2",
      "name": "4.4"
    }
  ]
}